apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-iam-operator
  labels:
     app.kubernetes.io/instance: ibm-iam-operator
     app.kubernetes.io/managed-by: ibm-iam-operator
     app.kubernetes.io/name: ibm-iam-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-iam-operator
  template:
    metadata:
      labels:
        name: ibm-iam-operator
        app.kubernetes.io/instance: ibm-iam-operator
        app.kubernetes.io/managed-by: ibm-iam-operator
        app.kubernetes.io/name: ibm-iam-operator
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-iam-operator
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: ibm-iam-operator
          # Replace this with the built image name
          image: quay.io/tirumalamannaru/ibm-iam-operator:cp3.0
          command:
          - ibm-iam-operator
          imagePullPolicy: Always
          env:
            - name: ICP_PLATFORM_AUTH_IMAGE
              value: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/icp-platform-auth-amd64:4.0.0
            - name: ICP_IDENTITY_PROVIDER_IMAGE
              value: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/icp-identity-provider-amd64:4.0.0
            - name: ICP_IDENTITY_MANAGER_IMAGE
              value: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/icp-identity-manager-amd64:4.0.0
            - name: IAM_POLICY_ADMINISTRATION_IMAGE
              value: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/iam-policy-administration-amd64:4.0.0
            - name: IAM_POLICY_DECISION_IMAGE
              value: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/iam-policy-decision-amd64:3.10.0
            - name: ICP_SECRET_WATCHER_IMAGE
              value: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/icp-secret-watcher-amd64:3.7.12
            - name: IAM_POLICY_CONTROLLER_IMAGE
              value: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/iam-policy-controller-amd64:3.7.12
            - name: ICP_IAM_ONBOARDING_IMAGE
              value: hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com/ibmcom/icp-iam-onboarding-amd64:3.10.0
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-iam-operator"
          resources:
            limits:
              cpu: 25m
              memory: 320Mi
            requests:
              cpu: 20m
              memory: 80Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
          - mountPath: /certs
            name: cluster-ca-cert
      volumes:
        - name: cluster-ca-cert
          secret:
            defaultMode: 420
            items:
            - key: tls.key
              path: ca.key
            - key: tls.crt
              path: ca.crt
            secretName: cs-ca-certificate-secret
