channels:
- currentCSV: ibm-iam-operator.v3.9.1
  name: beta
- currentCSV: ibm-iam-operator.v3.22.0
  name: v3.22
- currentCSV: ibm-iam-operator.v4.0.0
  name: v4
defaultChannel: v4
packageName: ibm-iam-operator
